rstring: "r\"" regex* "\""

?regex: character | word | group | pipe | class | all_quants

group: "(" regex+ ")"

pipe: regex+ "|" regex+

character: LETTER | NUMBER

word: WORD

range: NUMBER "-" NUMBER | LETTER "-" LETTER | character

class: "[" range* "]"

?all_quants: (group | character | class) ("*" | "+" | num_quant)

?num_quant: ("{" NUMBER "}") | ("{" (NUMBER ",")+ NUMBER?"}") | ("{" ("," NUMBER)+"}")

%ignore /\s+/
%import common.LETTER
%import common.NUMBER
%import common.WORD

